// GENERATED by tools/test-homework.mjs --write from the reference solutions. Do not edit.
// The numbers a correct HW1 reproduces, the same as the homework page and the WebGL runner.
using UnityEngine;

namespace CSS551.HW01
{
    public struct Check
    {
        public string Id, Label; public int Points; public double Tol; public double[] Want;
        public Check(string id, string label, int points, double tol, double[] want) { Id = id; Label = label; Points = points; Tol = tol; Want = want; }
    }

    public static class Expected
    {
        public static readonly Check[] Checks = {
            new Check("step60", "advance: position after 1 s at 60 frames per second", 10, 0.0001, new double[] { 3.0, 0.0, 0.0 }),
            new Check("step20", "advance: position after 1 s at 20 frames per second", 10, 0.0001, new double[] { 3.0, 0.0, 0.0 }),
            new Check("circle", "hitTest2D circle: inside, just outside, on the circle", 6, 0.0, new double[] { 1.0, 0.0, 1.0 }),
            new Check("segment", "hitTest2D segment: on it, at tol, beyond tol, past endpoint b", 7, 0.0, new double[] { 1.0, 1.0, 0.0, 0.0 }),
            new Check("segDot", "hitTest2D segment with a == b: within tol, beyond tol", 4, 0.0, new double[] { 1.0, 0.0 }),
            new Check("tri", "hitTest2D triangle (a, b, c): inside, outside, on an edge, on an edge's line outside", 6, 0.0, new double[] { 1.0, 0.0, 1.0, 0.0 }),
            new Check("triFlip", "hitTest2D triangle (a, c, b), the other winding: the same four points", 2, 0.0, new double[] { 1.0, 0.0, 1.0, 0.0 }),
            new Check("pointer", "classifyPointer: is each release a drag? (true = 'drag', false = 'click')", 10, 0.0, new double[] { 0.0, 0.0, 0.0, 1.0, 1.0 }),
            new Check("aimZ", "orientBasis: forward axis z (toward the target)", 15, 0.001, new double[] { -0.588348405415, 0.196116135138, -0.784464540553 }),
            new Check("aimX", "orientBasis: right axis x", 15, 0.001, new double[] { -0.8, 0.0, 0.6 }),
            new Check("aimY", "orientBasis: up axis y", 15, 0.001, new double[] { 0.117669681083, 0.980580675691, 0.156892908111 }),
        };
    }
}
