// GENERATED by tools/test-homework.mjs --write. Do not edit.
// The published inputs of HW1 (the same as lib/skeletons/checks.js).
using UnityEngine;

namespace CSS551.HW01
{
    public static class Inputs
    {
        public static readonly float speed = 3f;
        public static readonly Vector2 circle_center = new Vector2(200f, 150f);
        public static readonly float circle_r = 12f;
        public static readonly Vector2[] circle_pts = { new Vector2(205f, 154f), new Vector2(208f, 159f), new Vector2(212f, 150f) };
        public static readonly Vector2 segment_a = new Vector2(100f, 100f);
        public static readonly Vector2 segment_b = new Vector2(180f, 160f);
        public static readonly float segment_tol = 5f;
        public static readonly Vector2[] segment_pts = { new Vector2(140f, 130f), new Vector2(137f, 134f), new Vector2(134f, 138f), new Vector2(188f, 160f) };
        public static readonly Vector2 dot_a = new Vector2(300f, 80f);
        public static readonly Vector2 dot_b = new Vector2(300f, 80f);
        public static readonly float dot_tol = 5f;
        public static readonly Vector2[] dot_pts = { new Vector2(303f, 84f), new Vector2(304f, 84f) };
        public static readonly Vector2 triangle_a = new Vector2(50f, 50f);
        public static readonly Vector2 triangle_b = new Vector2(150f, 60f);
        public static readonly Vector2 triangle_c = new Vector2(90f, 140f);
        public static readonly Vector2[] triangle_pts = { new Vector2(95f, 80f), new Vector2(150f, 120f), new Vector2(100f, 55f), new Vector2(200f, 65f) };
        public static readonly Vector2 pointer_down = new Vector2(400f, 300f);
        public static readonly Vector2[] pointer_ups = { new Vector2(404f, 300f), new Vector2(403f, 302f), new Vector2(397f, 302f), new Vector2(403f, 303f), new Vector2(405f, 301f) };
        public static readonly Vector3 aim_pos = new Vector3(1f, 0.5f, 2f);
        public static readonly Vector3 aim_target = new Vector3(-2f, 1.5f, -2f);
        public static readonly Vector3 aim_up = new Vector3(0f, 1f, 0f);
    }
}
